jasypt.encryptor.password: ${JASYPT_ENCRYPTOR_PASSWORD}
spring:
  profiles:
    active: local
  swagger2:
    enabled: false
  mail:
    personal: XX官方邮件
    host: smtp.163.com
    username: 13600747016@163.com
    # 此处 password 为授权码
    password: ENC(rtE5S5utfbprjLVoLfhAvtj53dqpzwjQGZhnxADtdlY=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true
aliyun:
  oss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    secret-access: ENC(lRjG5ydrDnl5oRIGUaQNIdyut+mNoxvkVj2oekmbgN80i93FLfl+cA==)
    access-key: ENC(w1e6RkiL4tuTbasWXZL85UIVvXjfplXuTqV259ztRZ8=)

# EAGLE
eagle:
  hostname: http://127.0.0.1:8080
  amap: ENC(773e44N8XZaDGUKtmj3btJztElbCAhWYNCkSRMhj/wUiYtPs5nKQ3/JsTg9LzCGF)
  ip138: ENC(qcTFZLAY+7tDV4gKQ7xcl3vXs/ypMFx/wBUE0zf15SUBLKqB7xu3FsVpwOIktiiE)
