spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mariadb://mysql.localhost:3306/db_eagle?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: hocgin
    druid:
      validation-query: SELECT 1
      test-while-idle: true
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: none
  flyway:
    baseline-on-migrate: true
    enabled: false

mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:/**/xml/*.xml
