### 登录
POST {{host}}/api/account/authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "hocgin"
}

> {% client.global.set("auth_token", response.body.data); %}

### 账号详情
GET {{host}}/api/account/{id}
Content-Type: application/json

{
}

### 给账号授权角色
POST {{host}}/api/account/{id}/grant/role
Content-Type: application/json

{
}


### 注册会员
POST {{host}}/api/member
Content-Type: application/json

{
}

### 添加员工
POST {{host}}/api/staff
Content-Type: application/json

{
}

###
