### 新增权限
POST {{host}}/api/authority
Content-Type: application/json
Token: Bearer {{auth_token}}

{
  "title": "新增角色",
  "type": 1,
  "authorityCode": "权限授权码",
  "method": "GET",
  "uri": "/*",
  "enabled": 1,
  "sort": 1000
}

### 修改权限
PUT {{host}}/api/authority/{id}

### 权限详情
GET {{host}}/api/authority/{id}

### 权限列表
POST {{host}}/api/authority/_search

### 新增角色
POST {{host}}/api/role

### 修改角色
PUT {{host}}/api/role

### 角色详情
GET {{host}}/api/role/{id}

### 角色列表
POST {{host}}/api/role/_search

### 给角色授权权限
POST {{host}}/api/role/{id}/grant/authority

###