apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-eagle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eagle
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: eagle
    spec:
      containers:
        - name: eagle
          image: registry.cn-hongkong.aliyuncs.com/hocgin/eagle:latest
          imagePullPolicy: Always
          args: [ "--spring.profiles.active=${ACTIVE}" ]
          ports:
            - name: web-port
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: cm-service-env
          livenessProbe:
              httpGet:
                  path: "/actuator/health"
                  port: web-port
              initialDelaySeconds: 100
              periodSeconds: 10
              timeoutSeconds: 10
              successThreshold: 1
              failureThreshold: 5
          readinessProbe:
              initialDelaySeconds: 60
              timeoutSeconds: 3
              httpGet:
                  path: "/actuator/health"
                  port: web-port
---
apiVersion: v1
kind: Service
metadata:
  name: sv-eagle
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: eagle
